from __future__ import annotations

from mcp.server import Server

from resources.register_resources import register_resources
from tools.register_tools import register_tools
from version import SERVER_NAME, SERVER_VERSION


def create_mcp_server() -> Server:
    server = Server(
        SERVER_NAME,
        version=SERVER_VERSION,
        instructions="\n".join(
            [
                "# Unity-AI-Forge MCP Server v2.0.0 - Quick Reference",
                "AI駆動型Unity開発ツールキット。MCPサーバー + GameKitフレームワーク。3層構造（Low/Mid/High-Level）で効率的な開発を実現。",
                "",
                "## 🔴 Critical Rules (必ず守る)",
                "1. .metaファイルは絶対に編集しない（Unity自動管理、手動編集は参照破壊）",
                "2. 全Unity操作にMCPツール（unity_*）を使用",
                "3. 変更前に operation='inspect' で対象を確認",
                "4. 適切なレイヤーのツールを選択（Low→詳細制御、Mid→バッチ、High→ゲームシステム）",
                "5. コンパイルが必要な操作は自動待機（ブリッジ再接続で解除）",
                "",
                "## 🏗️ 3層アーキテクチャ",
                "",
                "### Low-Level CRUD (8ツール) - 基本操作",
                "Scene, GameObject, Component, Asset, ScriptableObject, Prefab, VectorSprite, ProjectSettings",
                "用途: 詳細な制御、単一オブジェクト操作、プロパティ精密設定",
                "",
                "### Mid-Level Batch (7ツール) - バッチ操作とプリセット",
                "Transform, RectTransform, Physics, Camera, UI, Audio, Input",
                "用途: 複数オブジェクト一括処理、プリセット適用、レイアウト調整",
                "",
                "### High-Level GameKit (5ツール) - ゲームシステム構築",
                "Actor, Manager, Interaction, UICommand, SceneFlow",
                "用途: ゲームメカニクス、ターン制御、シーン遷移、インタラクション",
                "",
                "## 基本ワークフロー",
                "1. 確認: unity_scene_crud(operation='inspect', includeHierarchy=True)",
                "2. 操作: 適切なレイヤーのツールで変更実施",
                "3. 検証: operation='inspect' で結果確認",
                "",
                "## 🎮 High-Level GameKit Tools (推奨: ゲームシステム構築)",
                "",
                "### GameKit Actor - ゲームアクター",
                "- 作成: unity_gamekit_actor(operation='create', actorId='player_001', actorType='player', behaviorProfile='2dPhysics'|'2dLinear'|'2dTileGrid'|'3dCharacterController'|'3dPhysics'|'3dNavMesh', controlMode='directController'|'aiAutonomous'|'uiCommand'|'scriptTriggerOnly', stats={'health': 100, 'speed': 5.0}, abilities=['Jump', 'Attack'])",
                "- 更新: unity_gamekit_actor(operation='update', actorId='...', stats={'health': 80})",
                "- 検査: unity_gamekit_actor(operation='inspect', actorId='...')",
                "",
                "### GameKit Manager - ゲームマネージャー",
                "- 作成: unity_gamekit_manager(operation='create', managerId='game_manager', managerType='turnBased'|'realtime'|'resourcePool'|'eventHub'|'stateManager', turnPhases=['PlayerTurn', 'EnemyTurn'], resourcePool={'actionPoints': 3}, dontDestroyOnLoad=True)",
                "- ターン進行: unity_gamekit_manager(operation='update', managerId='...', advancePhase=True)",
                "- リソース消費: unity_gamekit_manager(operation='update', managerId='...', consumeResource={'resourceName': 'actionPoints', 'amount': 1})",
                "",
                "### GameKit Interaction - インタラクション",
                "- 作成: unity_gamekit_interaction(operation='create', interactionId='door_trigger', triggerType='trigger'|'collision'|'raycast'|'proximity'|'input', actions=[{'type': 'changeScene', 'target': 'Level2'}], conditions=[{'type': 'tag', 'value': 'Player'}])",
                "- アクションタイプ: spawnPrefab, destroyObject, playSound, sendMessage, changeScene",
                "",
                "### GameKit UI Command - UIコマンドパネル",
                "- 作成: unity_gamekit_ui_command(operation='createCommandPanel', panelName='CommandPanel', commands=['Move', 'Attack', 'Defend'], layout='horizontal'|'vertical'|'grid', targetActorId='player_001')",
                "",
                "### GameKit SceneFlow - シーン遷移管理",
                "- 作成: unity_gamekit_sceneflow(operation='create', flowId='main_flow', scenes=[{'name': 'Title', 'path': 'Assets/Scenes/Title.unity', 'loadMode': 'single'}, {'name': 'Level1', 'path': '...', 'loadMode': 'additive', 'sharedGroups': ['UI', 'Audio']}], sharedSceneGroups={'UI': ['Assets/Scenes/GameUI.unity']}, transitions=[{'from': 'Title', 'to': 'Level1', 'trigger': 'StartGame'}])",
                "- 遷移: unity_gamekit_sceneflow(operation='transition', flowId='...', trigger='StartGame')",
                "",
                "## ⚡ Mid-Level Batch Tools (推奨: バッチ操作)",
                "",
                "### Transform Batch - 配置とリネーム",
                "- 円形配置: unity_transform_batch(operation='arrangeCircle', gameObjectPaths=['Obj1', 'Obj2'], radius=5.0, startAngle=0)",
                "- 直線配置: unity_transform_batch(operation='arrangeLine', gameObjectPaths=[...], startPosition={...}, endPosition={...})",
                "- 連番リネーム: unity_transform_batch(operation='renameSequential', gameObjectPaths=[...], baseName='Enemy', startIndex=1, padding=3)",
                "",
                "### RectTransform Batch - UIレイアウト",
                "- アンカー設定: unity_rectTransform_batch(operation='setAnchors', gameObjectPaths=[...], anchorMin={'x': 0, 'y': 0}, anchorMax={'x': 1, 'y': 1})",
                "- 親に整列: unity_rectTransform_batch(operation='alignToParent', gameObjectPaths=[...], preset='topLeft'|'center'|'bottomRight')",
                "- 分配: unity_rectTransform_batch(operation='distribute', gameObjectPaths=[...], direction='horizontal'|'vertical', spacing=10)",
                "",
                "### Physics Bundle - 物理プリセット",
                "- 2Dプリセット: unity_physics_bundle(operation='applyPreset2D', gameObjectPath='...', preset='dynamic'|'kinematic'|'static'|'character'|'platformer'|'topDown'|'vehicle'|'projectile')",
                "- 3Dプリセット: unity_physics_bundle(operation='applyPreset3D', gameObjectPath='...', preset='dynamic'|'kinematic'|'static'|'character'|'vehicle'|'projectile')",
                "",
                "### Camera Rig - カメラ設定",
                "- 作成: unity_camera_rig(operation='createRig', rigType='follow'|'orbit'|'splitScreen'|'fixed'|'dolly', cameraName='MainCamera', targetPath='Player', offset={'x': 0, 'y': 5, 'z': -10}, smoothSpeed=5.0)",
                "",
                "### UI Foundation - UI基礎要素",
                "- Canvas: unity_ui_foundation(operation='createCanvas', canvasName='GameUI', renderMode='screenSpaceOverlay'|'screenSpaceCamera'|'worldSpace')",
                "- Button: unity_ui_foundation(operation='createButton', buttonName='...', parentPath='Canvas', text='...', anchorPreset='center', width=200, height=60)",
                "",
                "### Audio Source Bundle - オーディオ設定",
                "- 作成: unity_audio_source_bundle(operation='createAudioSource', gameObjectPath='...', preset='music'|'sfx'|'ambient'|'voice'|'ui', audioClipPath='...', volume=1.0, loop=True)",
                "",
                "### Input Profile - 入力システム",
                "- 作成: unity_input_profile(operation='createPlayerInput', gameObjectPath='...', actionMapType='player'|'ui'|'vehicle', notificationBehavior='sendMessages'|'broadcastMessages'|'invokeUnityEvents')",
                "",
                "## 🔧 Low-Level CRUD Tools (詳細制御)",
                "",
                "### Scene & GameObject",
                "- 作成: unity_gameobject_crud(operation='create', name='...', parentPath='...')",
                "- 複数検索: unity_gameobject_crud(operation='findMultiple', pattern='Enemy*', maxResults=100)",
                "- 移動: unity_gameobject_crud(operation='move', gameObjectPath='...', parentPath='...')",
                "",
                "### Component",
                "- 追加: unity_component_crud(operation='add', gameObjectPath='...', componentType='UnityEngine.Rigidbody', propertyChanges={...})",
                "- 更新: unity_component_crud(operation='update', gameObjectPath='...', componentType='...', propertyChanges={...})",
                "- バッチ追加: unity_component_crud(operation='addMultiple', pattern='Enemy*', componentType='...', stopOnError=False, maxResults=100)",
                "",
                "### Asset & Script",
                "- テキストファイル作成: unity_asset_crud(operation='create', assetPath='Assets/Data/config.json', content='...')",
                "- 更新: unity_asset_crud(operation='update', assetPath='...', content='...')",
                "  ⚠️ C#スクリプト作成/更新後は自動コンパイル待機（60秒タイムアウト、ブリッジ再接続で解除）",
                "- インポーター設定: unity_asset_crud(operation='updateImporter', assetPath='...', propertyChanges={...})",
                "",
                "### ScriptableObject",
                "- 作成: unity_scriptableObject_crud(operation='create', typeName='MyGame.GameConfig', assetPath='Assets/Data/....asset', properties={...})",
                "- 検査: unity_scriptableObject_crud(operation='inspect', assetPath='...', includeProperties=True, propertyFilter=['version', 'maxPlayers'])",
                "- 更新: unity_scriptableObject_crud(operation='update', assetPath='...', properties={...})",
                "- 型検索: unity_scriptableObject_crud(operation='findByType', typeName='...', searchPath='Assets/Data', maxResults=100)",
                "",
                "### Prefab",
                "- 作成: unity_prefab_crud(operation='create', gameObjectPath='...', prefabPath='Assets/Prefabs/....prefab', includeChildren=True)",
                "- インスタンス化: unity_prefab_crud(operation='instantiate', prefabPath='...', targetPath='...', position={...}, rotation={...})",
                "- オーバーライド適用: unity_prefab_crud(operation='applyOverrides', gameObjectPath='...')",
                "- オーバーライド破棄: unity_prefab_crud(operation='revertOverrides', gameObjectPath='...')",
                "- アンパック: unity_prefab_crud(operation='unpack', gameObjectPath='...', unpackMode='outmostRoot'|'completely')",
                "",
                "### Vector Sprite (プロトタイプ用)",
                "外部アセット不要で即座に生成。ゲームジャム、プロトタイピング、プレースホルダーに最適。",
                "- プリミティブ: unity_vector_sprite_convert(operation='primitiveToSprite', primitiveType='circle'|'square'|'triangle'|'polygon', color={'r':1,'g':0,'b':0,'a':1}, outputPath='Assets/Sprites/....png', width=256, height=256)",
                "- 単色: unity_vector_sprite_convert(operation='createColorSprite', width=64, height=64, color={...}, outputPath='...')",
                "- SVG変換: unity_vector_sprite_convert(operation='svgToSprite', svgPath='...', outputPath='...', width=512, height=512)",
                "- テクスチャ→スプライト: unity_vector_sprite_convert(operation='textureToSprite', texturePath='...', pixelsPerUnit=100, filterMode='point'|'bilinear')",
                "",
                "### Project Settings",
                "- 読み取り: unity_projectSettings_crud(operation='read', category='player'|'quality'|'time'|'physics'|'audio'|'editor', property='...')",
                "- 書き込み: unity_projectSettings_crud(operation='write', category='...', property='...', value=...)",
                "- タグ追加: unity_projectSettings_crud(operation='addTag', tag='...')",
                "- レイヤー追加: unity_projectSettings_crud(operation='addLayer', layer='...')",
                "",
                "## ⚡ Performance & Best Practices",
                "",
                "### ツール選択ガイド:",
                "1. **ゲームシステム構築** → High-Level GameKit (Actor, Manager, Interaction, UICommand, SceneFlow)",
                "2. **複数オブジェクト処理** → Mid-Level Batch (Transform, RectTransform, Physics, Camera, UI, Audio, Input)",
                "3. **詳細な個別制御** → Low-Level CRUD (GameObject, Component, Asset, ScriptableObject, Prefab)",
                "",
                "### 高速化テクニック:",
                "1. includeProperties=False: コンポーネント存在確認のみ（10倍高速）",
                "2. propertyFilter: 必要なプロパティのみ取得",
                "3. maxResults: 大量操作時のタイムアウト防止（デフォルト1000）",
                "4. stopOnError=False: バッチ処理でエラー時も続行",
                "",
                "### バッチ操作（推奨）:",
                "❌ 避ける: ループ内で個別ツール呼び出し",
                "✅ 推奨: Mid-Level Batchツールまたは *Multiple 操作",
                "例: unity_transform_batch(operation='arrangeCircle', gameObjectPaths=[...])",
                "例: unity_component_crud(operation='addMultiple', pattern='Enemy*', ...)",
                "",
                "### コンパイル待機（自動）:",
                "- C#スクリプト作成/更新後、自動的にコンパイル待機",
                "- 待機中にブリッジが再接続されると即座に解除",
                "- タイムアウト: 60秒（設定変更不可）",
                "- レスポンスに compilationWait 情報が含まれる",
                "",
                "## 🎮 Game Development Workflow",
                "",
                "### 推奨開発フロー:",
                "1. **ゲームシステム設計** (High-Level GameKit)",
                "   - GameKit Actor: プレイヤー、敵、NPCの作成",
                "   - GameKit Manager: ターン制御、リソース管理",
                "   - GameKit SceneFlow: シーン遷移設計",
                "",
                "2. **インタラクション実装** (High-Level GameKit)",
                "   - GameKit Interaction: トリガーとアクション定義",
                "   - GameKit UICommand: UIからのコマンド送信",
                "",
                "3. **詳細調整** (Mid/Low-Level)",
                "   - Mid-Level: 物理、カメラ、UI、オーディオのプリセット適用",
                "   - Low-Level: 個別プロパティの微調整",
                "",
                "4. **演出追加** (最後)",
                "   - パーティクル、アニメーション、サウンド",
                "   - UI遷移、フィードバック演出",
                "",
                "### GameKit使用例:",
                "```python",
                "# 1. プレイヤーアクター作成",
                "unity_gamekit_actor(operation='create', actorId='player', behaviorProfile='2dPhysics', controlMode='directController', stats={'health': 100})",
                "",
                "# 2. ターン制マネージャー作成",
                "unity_gamekit_manager(operation='create', managerId='turn_mgr', managerType='turnBased', turnPhases=['PlayerTurn', 'EnemyTurn'])",
                "",
                "# 3. ドアトリガー作成",
                "unity_gamekit_interaction(operation='create', interactionId='door', triggerType='trigger', actions=[{'type': 'changeScene', 'target': 'Level2'}])",
                "",
                "# 4. シーンフロー設定",
                "unity_gamekit_sceneflow(operation='create', flowId='main', scenes=[...], transitions=[...])",
                "```",
                "",
                "## 🔧 Troubleshooting",
                "",
                "### 接続エラー",
                "1. unity_ping で接続確認",
                "2. Unity Editor: Tools > MCP Assistant が起動しているか確認",
                "3. ポート7077が使用可能か確認",
                "",
                "### コンパイルエラー",
                "- C#スクリプト作成/更新後は自動コンパイル待機",
                "- レスポンスの compilationWait 情報を確認",
                "- Unity Editorのコンソールログでエラー詳細を確認",
                "",
                "### タイムアウト",
                "1. maxResults を減らす（デフォルト1000 → 100以下）",
                "2. includeProperties=False で高速化",
                "3. stopOnError=False でバッチ操作続行",
                "4. Mid-Level Batchツールを使用（個別呼び出しより高速）",
                "",
                "### ブリッジ再接続",
                "- コンパイル中にブリッジが再接続された場合、自動的に待機解除",
                "- レスポンスに bridgeReconnected: true が含まれる",
                "- 再接続後、操作を再試行してください",
                "",
                "## 📋 Quick Reference",
                "",
                "### 全21ツール一覧:",
                "",
                "**High-Level GameKit (5):**",
                "unity_gamekit_actor, unity_gamekit_manager, unity_gamekit_interaction, unity_gamekit_ui_command, unity_gamekit_sceneflow",
                "",
                "**Mid-Level Batch (7):**",
                "unity_transform_batch, unity_rectTransform_batch, unity_physics_bundle, unity_camera_rig, unity_ui_foundation, unity_audio_source_bundle, unity_input_profile",
                "",
                "**Low-Level CRUD (8):**",
                "unity_scene_crud, unity_gameobject_crud, unity_component_crud, unity_asset_crud, unity_scriptableObject_crud, unity_prefab_crud, unity_vector_sprite_convert, unity_projectSettings_crud",
                "",
                "**Utility (1):**",
                "unity_ping",
                "",
                "### GameObject識別方法:",
                "- gameObjectPath: 階層パス（例: 'Canvas/Panel/Button'）",
                "- gameObjectGlobalObjectId: GlobalObjectId文字列（シーン再読み込み後も安定）",
                "",
                "### よくあるコンポーネントプロパティ:",
                "- Transform: position, rotation, localScale",
                "- RectTransform: anchoredPosition, sizeDelta, anchorMin, anchorMax, pivot",
                "- Rigidbody: mass, drag, useGravity, constraints",
                "- Rigidbody2D: mass, linearDamping, angularDamping, gravityScale, constraints",
                "- Camera: fieldOfView, clearFlags, backgroundColor",
                "",
                "### 命名規則:",
                "全ツール名は unity_* 形式（アンダースコア区切り）",
                "例: unity_gamekit_actor, unity_transform_batch, unity_gameobject_crud",
                "",
                "---",
                "SkillForUnity v1.8.0 - 21 Tools, 100+ Operations, 3-Layer Architecture",
            ]
        ),
    )

    register_resources(server)
    register_tools(server)

    return server

